### ISSUE TITLE
HardDisk not collected

### ISSUE THREAD

**Issue by rebelinux** [argaliev/ZenPacks.community.HPiLO#1]
Is there any requirement for the harddisk to be collected?

Nice zenpack!!! 

Thanks

**Comment by rebelinux** [comment]
Log Info	
UTI-TVSERV-01||/Status/HPiLO|3|No monitoring data for drives_backplanes

**Comment by rebelinux** [comment]
No monitoring data for health_at_a_glance

**Comment by argaliev** [comment]
The only requirement for the harddisk to be collected, is iLO version 3 or higher. I tested with version 3. If you have iLO 4, and harddisks not present, please tell me. 
As for events "No monitoring data for health_at_a_glance" this is a bug. I will release version with fix on monday.

**Comment by rebelinux** [comment]
i can confirm the zenpack works with ilo 2 but with ilo 4 no harddisk info are displayed.

**Comment by argaliev** [comment]
added support for harddisk with ilo 4. check updated version of zenpack.
can you provide info about you ilo 2? server model and ilo firmware version.
in my case, for server model DL360 G5 and firmware version 2.29, no available information  about harddisks.
